package com.timetable.timetable_api.model;

import jakarta.persistence.*;
import java.time.LocalDate; // Import for the DATE type

@Entity
@Table(name = "faculty")
public class Faculty {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "faculty_id")
    private Long id;

    // --- Relationship 1: One-to-One with User ---
    // This links the faculty profile to its login account.
    @OneToOne
    @JoinColumn(name = "user_id", referencedColumnName = "user_id", unique = true, nullable = false)
    private User user;

    // --- Relationship 2: Many-to-One with Department ---
    // Many faculty members can belong to one department.
    @ManyToOne
    @JoinColumn(name = "department_id", referencedColumnName = "department_id", nullable = false)
    private Department department;

    // --- Relationship 3: Many-to-One with DesignationConstraint ---
    // Many faculty members can share one designation (e.g., 'Professor').
    @ManyToOne
    @JoinColumn(name = "designation", referencedColumnName = "designation", nullable = false)
    private DesignationConstraint designationConstraint;

    // --- Standard Columns ---

    @Column(name = "first_name", nullable = false)
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "middle_initial")
    private String middleInitial;

    @Column(name = "middle_initial")
    private String middleInitial;

    // date_of_birth and date_of_joining removed in V6 migration

    // --- Getters and Setters ---
    // (Generated by IDE)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public DesignationConstraint getDesignationConstraint() {
        return designationConstraint;
    }

    public void setDesignationConstraint(DesignationConstraint designationConstraint) {
        this.designationConstraint = designationConstraint;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getMiddleInitial() {
        return middleInitial;
    }

    public void setMiddleInitial(String middleInitial) {
        this.middleInitial = middleInitial;
    }

    public String getName() {
        return (firstName + " " + (middleInitial != null ? middleInitial + " " : "")
                + (lastName != null ? lastName : "")).trim();
    }
}